version: '2.23.3'

services:

  redis:
    extends:
      service: redis
      file: redis.yml

  transactionpipeline:
    extends:
      service: transactionpipeline
      file: transactionpipeline.yml
    env_file:
      - properties.env
    depends_on:
      - redis
    ports:
      - "8080:8080"